spring:
   datasource:
       c3p0:
          driverClass: com.mysql.jdbc.Driver
          jdbcUrl: jdbc:mysql://localhost:3306/springboot_db
          user: root
          password: root
          maxPoolSize: 20
          minPoolSize: 10
          initialPoolSize: 10
   jpa:
      showSql: false
      properties:
        hibernate:
            format_sql: true
